### ISSUE TITLE
Why are seeds encoded differently based on which signing algorithm they are later used for?

### ISSUE THREAD

**Issue by thejohnfreeman** [ripple/ripple-address-codec#17]
Take a look at [these tests](https://github.com/ripple/ripple-address-codec/blob/master/src/xrp-codec.test.ts#L74-L102). The same keys (for example, `00000000000000000000000000000000` or `FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`) are encoded differently based on the signing algorithm used later to derive the private key, public key, and address. This is different from rippled in which seeds (always 16 random bytes) are always encoded the same way, regardless of which signing algorithm is used. Are seeds in this codebase meant to be like "tagged seeds"? Presently it has the consequence that someone can use `wallet_propose` from rippled to get a seed, keys, and address; fund that address; then pass the seed to this library and fail to derive the same address.

**Comment by sublimator** [comment]
The intention at one point was to implement this in rippled :/

Yes, tagged addresses.

**Comment by thejohnfreeman** [comment]
Thank you for the quick answer!
