### ISSUE TITLE
Add isValidSeed(str) function

### ISSUE THREAD

**Issue by mDuo13** [ripple/ripple-address-codec#200]
The library exposes `isValidXAddress(str)` and `isValidClassicAddress(str)` functions but does not provide the equivalent functionality for base58-encoded seeds. If you're taking user input and you need to confirm whether a pasted seed value is valid (proper base58 & checksum computes) you have to use try/catch on `decodeSeed(str)` or do some other even more roundabout check rather than getting a convenient boolean.

Adding an `isValidSeed(str)` function would serve that use case, and could be exported in higher-level libraries as well.

**Comment by intelliot** [comment]
Replaced by https://github.com/XRPLF/xrpl.js/issues/1811
