### ISSUE TITLE
destination tag

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-address-codec#7]
Just opening an issue here, cause an email notification reminded me of ripple. 

I once helped someone on Github with destination tag issues, and put my email on the issue, so now and then I get people pleading with me to help because they forget their destination tag on an exchange deposit ... 

Seems like an address format that encoded the address plus destination tag would be useful ...  

I think the idea was toyed with ... might be worth revisiting

@intelliot

**Comment by intelliot** [comment]
This is something we're looking into :)

**Comment by sublimator** [comment]
Might be useful:
https://github.com/ripple/x-address-codec#wait-what-if-we-wanted-to-create-a-prefix-for-the-new-nifty-spaceman-secrets

**Comment by sublimator** [comment]
I think there's already support for decoding multiple version types (see
the sEd prefix for seeds expected to yield a ed25119 seed)
but not sure about differing lengths ...

**Comment by sublimator** [comment]
yield an ed25519 *private key* I meant ...

**Comment by sublimator** [comment]
@intelliot 

@N3TC4T here is working on a very nice looking wallet for ripple (https://github.com/N3TC4T/artunis-mobile), and wants to move to using bech32 addresses too. He's also interested in signing directly using keypairs, see: https://github.com/ripple/ripple-lib/pull/769#issuecomment-335453888 

It seems ripple-keypairs/ripple-lib etc could be cleaned up with the use of this bech32 standard you mentioned, at the same time as adding destination tags. 

I'm sure @N3TC4T has some insights/ideas he could share. Thanks

**Comment by sublimator** [comment]
Seems I'm confused re: bip32 vs bech32 but I hope you two can sort it out :)

**Comment by WietseWind** [comment]
@sublimator @intelliot See https://github.com/ripple/ripple-address-codec/pull/9, preparing for https://github.com/xrp-community/standards-drafts/issues/6. I'll use that in an add on lib. that takes care of the encoding and decoding (with a simple api instead of what I added to the tests).

**Comment by nbougalis** [comment]
Thanks @WietseWind.

@sublimator, nice to see you. BECH32 would be neat but we opted not to use it.

As for BIP32 support, having hierarchies of keypairs would be neat. Note that _nothing_ stops someone from using BIP32 _today_ to derive key pairs to use with XRP Ledger. They simply won't have a secret seed and won't be able to use that keypair with wallets that require inputting a seed and implement the key derivation algorithm.

**Comment by sublimator** [comment]
Hey Nik

I have no dog in this fight re: bip32/bech32 vs whatever ...

Just make the “help me” emails stop!!! Lol

Note you could potentially use the findPrefix code to find a multibyte
prefix (slight pita to decode maybe) that creates “rTagged” or whatever ...
or maybe even a one byte prefix for ‘r’

Not sure what you guys planning the one byte prefix ( I think I saw in a
spec)

On mobile atm, afk

**Comment by sublimator** [comment]
Oh looks like happily it’s ‘r’ despite different payload lengths

**Comment by sublimator** [comment]
Because 0, I guess ...

**Comment by sublimator** [comment]
Hrmmmm, I wonder if u could actually find the leading bytes that matches
what you would have to encode the tag bytes to keep the leading prefix as
the actual ripple address.

Just for fun, you probably could. Whether you should??

**Comment by sublimator** [comment]
Actually, in theory you could have a VL suffix repr TLVs ...

**Comment by sublimator** [comment]
*eg. *

*rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B*SrQCgpmyU44mPXaz4

decode it, strip the trailing 4 bytes checksum and ...
uint64 dt = 1

>

**Comment by sublimator** [comment]
Stupid email formatting:

eg.

**rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B**SrQCgpmyU44mPXaz4

b58 decode it, strip the trailing 4 bytes checksum and ...
UInt64BE dt = 1

**Comment by sublimator** [comment]
Pity 0 is not part of the ripple alphabet

**Comment by sublimator** [comment]
Obviously u would have to do some fiddling for VL suffix but it would be
doable ...

**Comment by sublimator** [comment]
Re: “The "tight" format results in an address that shares no common prefix
with the classic address, except, perhaps, by chance.”

The payload last two bytes could encode the length of the actual address as
bas58, and the length of the payload.

So u could decode the whole string ...

Yada yada yada

Will make impl when get a chance ...

**Comment by intelliot** [comment]
We'll be going with https://xrpaddress.info/ since it has been adopted by the community. If someone would like to open a PR to add support in this library, feel free. I recommend building on https://github.com/ripple/ripple-address-codec/pull/8 , using TypeScript, and relying on no dependencies.
